export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_NEW_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';

export const SET_PLACE_PHOTOS = 'SET_PLACE_PHOTOS';
